# Generated by Django 5.1.1 on 2024-09-13 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='compte',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Libellé du Compte'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='number',
            field=models.CharField(max_length=6, verbose_name='Numéro Compte'),
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('date_application', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_application'],
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouvement', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=30, verbose_name='Type de mouvement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Montant du mouvemnt')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.compte', verbose_name='Compte comptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.ecriture', verbose_name='Numéro Ecriture')),
            ],
        ),
    ]
