# Generated by Django 5.1.1 on 2024-09-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_alter_compte_options_alter_compte_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriture',
            name='date_application',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ecriture',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Libellé'),
        ),
    ]
